/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
Title: Tenhun Falling spaceman (FanArt)
*/

import React, { useEffect, useRef, useMemo } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useMotionValue, useSpring } from "motion/react";
import { useFrame } from "@react-three/fiber";

export function Astronaut(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/tenhun_falling_spaceman_fanart.glb"
  );
  const { actions } = useAnimations(animations, group);
  
  useEffect(() => {
    if (animations.length > 0 && actions[animations[0].name]) {
      actions[animations[0].name].play();
    }
    return () => {
      // Cleanup animations
      Object.values(actions).forEach((action) => {
        if (action) action.stop();
      });
    };
  }, [actions, animations]);

  const yPosition = useMotionValue(5);
  const ySpring = useSpring(yPosition, { damping: 30, stiffness: 100 });
  useEffect(() => {
    ySpring.set(-1);
  }, [ySpring]);
  
  useFrame(() => {
    if (group.current) {
      group.current.position.y = ySpring.get();
    }
  });

  // Memoize materials to prevent unnecessary re-renders
  const material = useMemo(() => materials["AstronautFallingTexture.png"], [materials]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={[-Math.PI / 2, -0.2, 2.2]}
      scale={props.scale || 0.3}
      position={props.position || [1.3, -1, 0]}
      frustumCulled
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model">
          <group name="Root">
            <group name="metarig">
              <primitive object={nodes.metarig_rootJoint} />
              <skinnedMesh
                name="Cube001_0"
                geometry={nodes.Cube001_0.geometry}
                material={material}
                skeleton={nodes.Cube001_0.skeleton}
                frustumCulled
              />
              <skinnedMesh
                name="Cube005_0"
                geometry={nodes.Cube005_0.geometry}
                material={material}
                skeleton={nodes.Cube005_0.skeleton}
                frustumCulled
              />
              <skinnedMesh
                name="Cube002_0"
                geometry={nodes.Cube002_0.geometry}
                material={material}
                skeleton={nodes.Cube002_0.skeleton}
                frustumCulled
              />
              <skinnedMesh
                name="Plane_0"
                geometry={nodes.Plane_0.geometry}
                material={material}
                skeleton={nodes.Plane_0.skeleton}
                frustumCulled
              />
              <skinnedMesh
                name="Cube008_0"
                geometry={nodes.Cube008_0.geometry}
                material={material}
                skeleton={nodes.Cube008_0.skeleton}
                frustumCulled
              />
              <skinnedMesh
                name="Cube004_0"
                geometry={nodes.Cube004_0.geometry}
                material={material}
                skeleton={nodes.Cube004_0.skeleton}
                frustumCulled
              />
              <skinnedMesh
                name="Cube003_0"
                geometry={nodes.Cube003_0.geometry}
                material={material}
                skeleton={nodes.Cube003_0.skeleton}
                frustumCulled
              />
              <skinnedMesh
                name="Cube_0"
                geometry={nodes.Cube_0.geometry}
                material={material}
                skeleton={nodes.Cube_0.skeleton}
                frustumCulled
              />
              <skinnedMesh
                name="Cube009_0"
                geometry={nodes.Cube009_0.geometry}
                material={material}
                skeleton={nodes.Cube009_0.skeleton}
                frustumCulled
              />
              <skinnedMesh
                name="Cube011_0"
                geometry={nodes.Cube011_0.geometry}
                material={material}
                skeleton={nodes.Cube011_0.skeleton}
                frustumCulled
              />
              <group name="Cube001" />
              <group name="Cube005" />
              <group name="Cube002" />
              <group name="Plane" />
              <group name="Cube008" />
              <group name="Cube004" />
              <group name="Cube003" />
              <group name="Cube" />
              <group
                name="Cube009"
                rotation={[-2.708, 0.013, -1.447]}
                scale={1.307}
              />
              <group name="Cube011" />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

// Preload model with optimizations
useGLTF.preload("/models/tenhun_falling_spaceman_fanart.glb", {
  // Add any DRACO loader options if available
});
